### ISSUE TITLE
Open to view by all?

### ISSUE THREAD

**Issue by bcooney** [synox/open-life-tracker#1]
Hey there,

Maybe a stupid question, but any tips on making the entries public to view by all? I'd like to be able to enter data, save it, then have someone else see it (as a means of encouraging me to stay on my target). I have a fork of your work going and would like to figure this out. Thanks a lot! It's a great tool.

**Comment by synox** [comment]
The data is Only saved in your browser. No you can not share the entries. To do so would not be hard with php or nodejs.
